# Generated by Django 2.2.5 on 2019-09-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_num', models.IntegerField(default=0)),
                ('q_text', models.CharField(max_length=256)),
                ('component', models.CharField(max_length=64)),
                ('ans_a', models.CharField(max_length=128)),
                ('ans_b', models.CharField(max_length=128)),
                ('ans_c', models.CharField(max_length=128)),
                ('ans_d', models.CharField(max_length=128)),
                ('discussion', models.CharField(max_length=1024)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='minefield.Person')),
            ],
        ),
    ]
