# Generated by Django 2.2.5 on 2019-09-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minefield', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiebreaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_num', models.IntegerField(default=0)),
                ('q_text', models.CharField(max_length=256)),
                ('component', models.CharField(max_length=64)),
                ('ans_a', models.CharField(max_length=128)),
                ('ans_b', models.CharField(max_length=128)),
                ('ans_c', models.CharField(max_length=128)),
                ('ans_d', models.CharField(max_length=128)),
                ('correct_ans', models.CharField(max_length=8)),
                ('discussion', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('person', 'q_num')},
        ),
    ]
