# Generated by Django 2.1 on 2019-09-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minefield', '0003_auto_20190913_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(default='student', max_length=16),
        ),
    ]
