# Generated by Django 2.2.5 on 2019-10-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minefield', '0004_auto_20190913_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiebreaker',
            name='person',
            field=models.CharField(default='TIEBREAKER', max_length=32),
        ),
    ]
